Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/09/2023
Var
// Seção de Declarações das variáveis 
primeiro_num, segundo_num,soma,subtracao,multiplicar:inteiro
divisao:real
//soma:inteiro

Inicio
// Seção de Comandos, procedimento,
escreval("Usuario, insira um numero desejado: ")
leia(primeiro_num)
escreval ("")

escreva("Usuario, insira o segundo numeoro:")
leia(segundo_num)
escreval("")

soma<- primeiro_num + segundo_num
escreval("O valor da soma e :",soma)

subtracao<- primeiro_num - segundo_num
escreval("valor da subtracao e:", subtracao )

multiplicar<- primeiro_num * segundo_num
escreval(" o valor da multiplicar e :", multiplicar)

divisao<-primeiro_num / segundo_num
escreval("o valor da divisao e:", divisao)

Fimalgoritmo
